version: "3.9"
services:
  postgres:
    environment:
      POSTGRES_DB: pet_family
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
    postgres-data:    